#!/usr/bin/env bash

dry_run="0"
if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

copy_dir() {
    log "Copying files from $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        log "Found configs: $configs"
        for config in $configs; do
            dir=${2%/}/${config#./}
            
            log "Removing $dir"
            if [[ $dry_run == "0" ]]; then
                rm -rf $dir
            fi
            
            log "Copying $config to $dir"
            if [[ $dry_run == "0" ]]; then
                cp -r $config $dir
            fi
        done
    )
    popd &> /dev/null
}

copy_file() {
    log "Removing $2"
    if [[ $dry_run == "0" ]]; then
        rm $2
    fi

    log "Copying $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp $1 $2
    fi
}

# copy_dir .config $HOME/.config
copy_file ./env/.zshrc $HOME/.zshrc
