#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
grep=""
dry_run="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry_run="1"
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
	    echo "$1"
    fi
}

check_homebrew() {
    if ! command -v brew > /dev/null; then
        log "Homebrew is not installed, installing..."
        if [[ $dry_run == "0" ]]; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
    else
        log "Homebrew is already installed"
    fi
}

install_brew_packages() {
    log "Installing brew packages..."
    packages=$(cat $script_dir/brew/packages.txt)
    for package in $packages; do
        log "Installing package: $package..."
        if [[ $dry_run == "0" ]]; then
            brew install $package
        fi
    done

    log "Installing brew cask packages..."
    cask_packages=$(cat $script_dir/brew/casks.txt)
    for package in $cask_packages; do
        log "Installing cask package: $package..."
        if [[ $dry_run == "0" ]]; then
            brew install --cask $package
        fi
    done
}

setup_zsh() {
    log "Setting up zsh..."
    if [[ $dry_run == "0" ]]; then
        log "Change shell to zsh..."
        sudo chsh -s $(which zsh)
        log "Installing oh-my-zsh..."
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi
}

setup_git() {
    log "Setting up git..."
    if [[ $dry_run == "0" ]]; then
        log "git config --global user.name \"Lukas Andersen\""
        git config --global user.name "Lukas Andersen"
        log "git config --global user.email \"luke@slate71.com\""
        git config --global user.email "luke@slate71.com"
    fi
}

run() {
    check_homebrew
    install_brew_packages
    setup_zsh
    setup_git
}

run
